apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret  # Specify the secret to pull images from GHCR
      containers:
        - name: react-app
          image: ghcr.io/skarthickct/gitops-01:483283b4344b155b2495977970c99976004d0317
          imagePullPolicy: Always
          ports:
            - containerPort: 80
