apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/skarthickct/gitops-01:ac7b9cf70979e7c5d84370de6086ed3c65dd3bbf
          imagePullPolicy: Always
          ports:
            - containerPort: 80
