apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/skarthickct/gitops-01@sha256:d673d1773ba7e89f0288268c9961b45766f6ac5f22c84865d1a5bdc0072bca9c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
