apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret  
      containers:
        - name: react-app
          image: ghcr.io/skarthickct/gitops-01:942b076c47aa3634267e19d216c30c2e29bbddd5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
